import Head from "next/head";
import Jumbotron from "../components/Jumbotron/Jumbotron";
import Nav from "../components/Nave/Nav";
import DefaultLayout from "../layout/Default";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Exploring Nest.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DefaultLayout>
          <Jumbotron />
        </DefaultLayout>
      </main>
    </div>
  );
}
